---
- hosts: hadoop
  remote_user: root
  
  tasks:
        - name: install package
          yum: name=nginx state=present
        - name: copy tempalte for centos 7
          template: src=nginx.conf7.j2 dest=/etc/nginx/nginx.conf
          when: ansible_distribution_major_version=="7"
          notify: restart nginx
        - name: copy tempalte for centos 6
          template: src=nginx.conf6.j2 dest=/etc/nginx/nginx.conf
          when: ansible_distribution_major_version=="6"
          notify: restart nginx
        - name: start service
          service: name=nginx state=started enabled=no
  handlers:
        - name: restart nginx
          service: name=nginx state=restarted enabled=no